apps:
  argo-cd:
    enabled: true
  homepage:
    enabled: true
  cert-manager:
    enabled: true
  directus:
    enabled: true
  docker-registry:
    enabled: true
  cloudflared:
    enabled: true
  code-server:
    enabled: true
  ghost:
    enabled: true
  finance-app-database-service:
    enabled: true
  finance-frontend:
    enabled: true
  grafana:
    enabled: true
  ingress-nginx:
    enabled: true
  loki:
    enabled: true
  mimir:
    enabled: true
  openclaw:
    enabled: true
  openclaw-operator:
    enabled: true
  openfaas:
    enabled: false
  opentelemetry-collector:
    enabled: true
  postgresql:
    enabled: true
  prometheus:
    enabled: true
  promtail:
    enabled: true
  scraper-manager:
    enabled: true
  sentinel-rbac:
    enabled: true
  tekton-ci:
    enabled: true
  tekton-dashboard:
    enabled: true
  tekton-pipeline:
    enabled: true
  tekton-triggers:
    enabled: true
  tempo:
    enabled: true
  uptime-kuma:
    enabled: true
  yfinance-wrapper:
    enabled: true
  forge-postgresql:
    enabled: true
  forge-platform:
    enabled: true
  forge-admin:
    enabled: true
  forge-portal:
    enabled: true
