apps:
  argo-cd:
    enabled: true
  docker-registry:
    enabled: true
  finance-app-database-service:
    enabled: false
  grafana:
    enabled: true
  ingress-nginx:
    enabled: true
  loki:
    enabled: false
  mimir:
    enabled: false
  openfaas:
    enabled: false
  opentelemetry-collector:
    enabled: false
  postgresql:
    enabled: true
  prometheus:
    enabled: true
  scraper-manager:
    enabled: false
  tekton-dashboard:
    enabled: false
  tekton-pipeline:
    enabled: false
  tekton-pipeline-hello-world:
    enabled: false
  tekton-triggers:
    enabled: false
  tempo:
    enabled: false
  uptime-kuma:
    enabled: true
  yfinance-wrapper:
    enabled: false
