apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openclaw.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.openclaw.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.openclaw.name }}
    app.kubernetes.io/instance: {{ .Values.openclaw.name }}
  ports:
    - name: gateway
      port: 18789
      targetPort: 18790
      protocol: TCP
    - name: canvas
      port: 18793
      targetPort: 18794
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
