apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Infrastructure:
        - Grafana:
            - abbr: GR
              href: https://grafana.lucas.engineering
        - Prometheus:
            - abbr: PR
              href: https://prometheus.lucas.engineering
        - ArgoCD:
            - abbr: AR
              href: https://argocd.lucas.engineering
        - Uptime:
            - abbr: UP
              href: https://uptime.lucas.engineering
    - Finance:
        - Finance:
            - abbr: FI
              href: https://finance.lucas.engineering
        - API:
            - abbr: AP
              href: https://finance-db.lucas.engineering
        - YFinance:
            - abbr: YF
              href: https://yfinance.lucas.engineering
    - Tools:
        - OpenClaw:
            - abbr: OC
              href: https://openclaw.lucas.engineering
        - Tekton:
            - abbr: TK
              href: https://tekton.lucas.engineering
        - OpenFaaS:
            - abbr: FA
              href: https://openfaas.lucas.engineering
        - Registry:
            - abbr: RG
              href: https://registry.lucas.engineering
    - Content:
        - Blog:
            - abbr: BL
              href: https://blog.lucas.engineering
        - Directus:
            - abbr: DR
              href: https://admin.reefusion.lucas.engineering

  services.yaml: |
    []

  widgets.yaml: |
    []

  settings.yaml: |
    title: Lucas Engineering

  docker.yaml: |
    ---

  kubernetes.yaml: |
    ---
