apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-manager
spec:
  template:
    spec:
      containers:
      - name: scraper-manager
        image: docker.lucas.engineering/scraper_manager:0.1
      restartPolicy: Never
  backoffLimit: 1
