apiVersion: batch/v1
kind: Job
metadata:
  generateName: scraper-manager-
spec:
  template:
    spec:
      containers:
      - name: scraper-manager
        image: docker.lucas.engineering/scraper_manager:0.5
      restartPolicy: Never
  backoffLimit: 1