apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    {{- include "uptime-kuma.labels" (index .Subcharts "uptime-kuma") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
