{{- if (index .Values.apps "code-server").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/lucas_engineering.git
    path: charts/code-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
