{{- if (index .Values.apps "data-log-visual").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-log-visual
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/data-log-visual.git
    path: charts/data-log-visual
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
