apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  finalizers:
  - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/lward27/lucas_engineering.git
#     path: charts/elasticsearch
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       selfHeal: true