apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yfinance-wrapper
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/finance_app_database_service.git
    path: deployment.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true