{{- if (index .Values.apps "forge-platform").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forge-platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/forge.git
    path: charts/forge-platform
    targetRevision: HEAD
    helm:
      valuesObject:
          forgePlatform:
            ingress:
              annotations:
                cert-manager.io/private-key-rotation-policy: "Never"
                cert-manager.io/revision-history-limit: "2147483647"
  destination:
    server: https://kubernetes.default.svc
    namespace: forge-platform
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
