{{- if (index .Values.apps "forge-admin").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forge-admin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/forge.git
    path: charts/forge-admin
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: forge-platform
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
