{{- if (index .Values.apps "openfaas").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/lucas_engineering.git
    path: charts/openfaas
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openfaas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
