apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipeline-hello-world
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lward27/lucas_engineering.git
    path: charts/tekton-pipeline-hello-world
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  namespaceResourceBlacklist:
  - group: tekton.dev
    kind: TaskRun
  - group: tekton.dev
    kind: PipelineRun
  syncPolicy:
    automated:
      selfHeal: true