apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel-rbac.name" . }}
  namespace: {{ include "sentinel-rbac.namespace" . }}
  labels:
    {{- include "sentinel-rbac.labels" . | nindent 4 }}
automountServiceAccountToken: true
