apiVersion: v1
kind: Service
metadata:
  name: finance-frontend
spec:
  selector:
    app: finance-frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-frontend
spec:
  selector:
    matchLabels:
      app: finance-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: finance-frontend
    spec:
      containers:
      - name: finance-frontend
        image: registry.lucas.engineering/finance_frontend:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: finance.lucas.engineering
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finance-frontend
            port:
              number: 8080
