uptime-kuma:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/private-key-rotation-policy: "Never"
      cert-manager.io/revision-history-limit: "2147483647"
    hosts:
      - host: uptime.lucas.engineering
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - uptime.lucas.engineering
        secretName: uptime-lucas-engineering-tls
