uptime-kuma:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: uptime.lucas.engineering
        paths:
          - path: /
            pathType: ImplementationSpecific
