apiVersion: v1
kind: Service
metadata:
  name: yfinance-wrapper
spec:
  selector:
    app: yfinance-wrapper
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfinance-wrapper
spec:
  selector:
    matchLabels:
      app: yfinance-wrapper
  replicas: 1
  template:
    metadata:
      labels:
        app: yfinance-wrapper

    spec:
      containers:
      - name: yfinance-wrapper
        image: docker.lucas.engineering/yfinance_wrapper:0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: TEST_VARIABLE
          value: "Value of the test variable"
        ports:
        - containerPort: 8000