apiVersion: v1
kind: Service
metadata:
  name: yfinance-wrapper
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8090'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: yfinance-wrapper
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfinance-wrapper
spec:
  selector:
    matchLabels:
      app: yfinance-wrapper
  replicas: 1
  template:
    metadata:
      labels:
        app: yfinance-wrapper
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: yfinance-wrapper
        image: registry.lucas.engineering/yfinance_wrapper:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TEST_VARIABLE
          value: "Value of the test variable"
        ports:
        - containerPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yfinance-wrapper
spec:
  ingressClassName: nginx
  rules:
  - host: yfinance.lucas.engineering
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yfinance-wrapper
            port:
              number: 8090