apiVersion: v1
kind: Service
metadata:
  name: yfinance-wrapper
spec:
  selector:
    app: yfinance-wrapper
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfinance-wrapper
spec:
  selector:
    matchLabels:
      app: yfinance-wrapper
  replicas: 1
  template:
    metadata:
      labels:
        app: yfinance-wrapper
    spec:
      containers:
      - name: yfinance-wrapper
        image: registry.lucas.engineering/yfinance_wrapper:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_SERVICE_NAME
          value: "yfinance-wrapper"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=production,service.namespace=apps-prod"
        ports:
        - containerPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yfinance-wrapper
spec:
  ingressClassName: nginx
  rules:
  - host: yfinance.lucas.engineering
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yfinance-wrapper
            port:
              number: 8090
