apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: registry.lucas.engineering/yfinance_wrapper
    newName: registry.lucas.engineering/yfinance_wrapper
    digest: sha256:850341f37100a0e90711b54733e06eeb52cb268244c6bbc07c25ef1b3c932cce
