apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: registry.lucas.engineering/yfinance_wrapper
  newName: registry.lucas.engineering/yfinance_wrapper:git-da4e3cd8a4c33d2b359e4e521525203da32ecf18
  digest: sha256:f1cfc06fcac62d7c37a4d7dc87237e2abe02df0d9c3824a7521c5359058879c1
