apiVersion: v1
kind: ServiceAccount
metadata:
  name: epheros-ci
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: epheros-ci
    app.kubernetes.io/part-of: epheros
automountServiceAccountToken: false

