docker-registry:
  configPath: /etc/distribution
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    hosts:
      - registry.lucas.engineering
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi