docker-registry:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    hosts:
      - registry.lucas.engineering
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi