apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nanoclaw.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.nanoclaw.name }}
automountServiceAccountToken: false
