image:
  repository: timescale/timescaledb
  tag: latest-pg17
  pullPolicy: IfNotPresent

auth:
  postgresPassword: "topsecretpassword"
  database: "testdb"

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi

service:
  type: ClusterIP
  port: 5432

persistence:
  size: 8Gi
  storageClass: local-path
