image:
  repository: timescale/timescaledb
  tag: latest-pg17
  pullPolicy: IfNotPresent

auth:
  database: "testdb"
  existingSecret: "postgresql-auth"
  passwordKey: "postgres-password"

financeApp:
  database: "finance_app"
  user: "finance_app_user"

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi

service:
  type: ClusterIP
  port: 5432

persistence:
  size: 8Gi
  storageClass: local-path
