grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: false
  service:
    type: ClusterIP
  persistence:
    enabled: true
  initChownData:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.lucas.engineering
    tls:
      - hosts:
          - grafana.lucas.engineering
        secretName: grafana-lucas-engineering-tls
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc
          access: proxy
          isDefault: true
        - name: Mimir
          uid: mimir
          type: prometheus
          url: http://mimir-gateway.monitoring.svc/prometheus
          access: proxy
          isDefault: false
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring.svc
          access: proxy
          isDefault: false
          jsonData:
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: '"trace_id":"(\w+)"'
                name: TraceID
                url: "$${__value.raw}"
                urlDisplayLabel: View Trace
        - name: Tempo
          uid: tempo
          type: tempo
          url: http://tempo.monitoring.svc.cluster.local:3200
          access: proxy
          isDefault: false
          jsonData:
            nodeGraph:
              enabled: true
            tracesToLogs:
              datasourceUid: loki
              filterByTraceID: true
              spanStartTimeShift: "-1h"
              spanEndTimeShift: "1h"
              tags:
                - key: service.name
                  value: app
            serviceMap:
              datasourceUid: mimir
