grafana:
  service: 
    type: LoadBalancer
    port: 8083
  persistence:
    enabled: true
  spec:
    containers:
      resources:
        limits:
          cpu: 1000m
          memory: 2048Mi
        requests:
          cpu: 500m
          memory: 1024Mi