grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: true
  initChownData:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.lucas.engineering
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc
          access: proxy
          isDefault: true
          uid: prometheus
        - name: Mimir
          type: prometheus
          url: http://mimir-gateway.monitoring.svc/prometheus
          access: proxy
          isDefault: false
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring.svc
          access: proxy
          isDefault: false
          uid: loki
        - name: Tempo
          type: tempo
          url: http://tempo.monitoring.svc.cluster.local:3200
          access: proxy
          isDefault: false
          uid: tempo
          jsonData:
            tracesToLogsV2:
              datasourceUid: loki
              filterByTraceID: true
              filterBySpanID: true
            tracesToMetrics:
              datasourceUid: prometheus
            serviceMap:
              datasourceUid: prometheus
            nodeGraph:
              enabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      otel-collector:
        gnetId: 15983
        revision: 1
        datasource: Prometheus
      fastapi:
        gnetId: 16110
        revision: 1
        datasource: Prometheus
