grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: true
  initChownData:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.lucas.engineering
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc
          access: proxy
          isDefault: true
        - name: Mimir
          type: prometheus
          url: http://mimir-gateway.monitoring.svc/prometheus
          access: proxy
          isDefault: false
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring.svc
          access: proxy
          isDefault: false
        - name: Tempo
          type: tempo
          url: http://tempo.monitoring.svc.cluster.local:3200
          access: proxy
          isDefault: false
          jsonData:
            nodeGraph:
              enabled: true
