apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-staging
resources:
  - ../../yfinance-wrapper
  - network-policy.yaml
images:
  - name: registry.lucas.engineering/yfinance_wrapper
    digest: sha256:33f1a08b74c82fb5dc01ef0ebef8a1fa5e2fc0ac78be17dadd1f74bbf1e319ca
patches:
  - path: deployment-patch.yaml
  - target:
      kind: Ingress
      name: yfinance-wrapper
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: yfinance-wrapper
