apiVersion: v1
kind: Service
metadata:
  name: k3s-buildkit
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: k3s-buildkit
    app.kubernetes.io/part-of: tekton-ci
spec:
  type: ClusterIP
  ports:
    - name: buildkit
      port: 12340
      targetPort: 12340
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: k3s-buildkit-ipv4
  namespace: {{ .Values.namespace }}
  labels:
    kubernetes.io/service-name: k3s-buildkit
    app.kubernetes.io/name: k3s-buildkit
    app.kubernetes.io/part-of: tekton-ci
addressType: IPv4
ports:
  - name: buildkit
    protocol: TCP
    port: 12340
endpoints:
  - addresses: ["192.168.50.145"]
    conditions:
      ready: true
