apiVersion: v1
kind: Service
metadata:
  name: financeapp
spec:
  selector:
    app: financeapp
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8084
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeapp
spec:
  selector:
    matchLabels:
      app: financeapp
  replicas: 0
  template:
    metadata:
      labels:
        app: financeapp
    spec:
      containers:
      - name: financeapp
        image: docker.lucas.engineering/financeapp:0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000