openfaas:
  serviceType: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - host: openfaas.lucas.engineering
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway
              port:
                number: 8080