openfaas:
  serviceType: ClusterIP
  clusterRole: true
  alertmanager:
    create: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - host: openfaas.lucas.engineering
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway
              port:
                number: 8080
    tls:
    - hosts:
      - openfaas.lucas.engineering
      secretName: openfaas-lucas-engineering-tls